### ISSUE TITLE
HostsApi.lists_hosts can't parse Macos/Darwin hosts

### ISSUE THREAD

**Issue by ls-devon-hakel-kinko** [DataDog/datadog-api-client-python#1087]
**Describe the bug**

Calling `HostsApi.list_hosts()` will fail if one or more of the hosts is of type Macos/Darwin.
This is because the library expects the `nix_v` metadata field to not be `None`. However that field only seems to be set on linux hosts.

**To Reproduce**

1. Run the datadog agent on a macos host
2. Confirm the host shows up in your infrastructure list
3. Run the basic list_host [example](https://github.com/DataDog/datadog-api-client-python/blob/3b80e4331586cf979c77dce489f02caa815bb9db/examples/v1/hosts/ListHosts.py#L11)

**Expected behavior**
A response is returned without errors

**Actual behavior**

The stack trace I consistently get when the library fails to convert the `None` values.

```
Traceback (most recent call last):
  File "/home/user/Code/datadog-cost-allocation/src/hack/get_untagged_hosts.py", line 41, in main
    response = api_instance.list_hosts(count=1000)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/api/hosts_api.py", line 254, in list_hosts
    return self._list_hosts_endpoint.call_with_http_info(**kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/api_client.py", line 738, in call_with_http_info
    return self.api_client.call_api(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/api_client.py", line 362, in call_api
    return self._call_api(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/api_client.py", line 152, in _call_api
    return_data = self.deserialize(response_data, response_type, _check_type)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/api_client.py", line 242, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1593, in validate_and_convert_types
    return attempt_convert_item(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1492, in attempt_convert_item
    raise conversion_exc
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1484, in attempt_convert_item
    return deserialize_model(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1403, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 42, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 341, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/model/host_list_response.py", line 55, in _from_openapi_data
    self = super(HostListResponse, cls)._from_openapi_data(kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 642, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 196, in __setattr__
    self[attr] = value
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 567, in __setitem__
    self.set_attribute(name, value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 165, in set_attribute
    value = validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1639, in validate_and_convert_types
    validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1593, in validate_and_convert_types
    return attempt_convert_item(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1492, in attempt_convert_item
    raise conversion_exc
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1484, in attempt_convert_item
    return deserialize_model(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1403, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 42, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 341, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/model/host.py", line 112, in _from_openapi_data
    self = super(Host, cls)._from_openapi_data(kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 642, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 196, in __setattr__
    self[attr] = value
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 567, in __setitem__
    self.set_attribute(name, value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 165, in set_attribute
    value = validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1593, in validate_and_convert_types
    return attempt_convert_item(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1492, in attempt_convert_item
    raise conversion_exc
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1484, in attempt_convert_item
    return deserialize_model(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1403, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 42, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 341, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/model/host_meta.py", line 117, in _from_openapi_data
    self = super(HostMeta, cls)._from_openapi_data(kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 642, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 196, in __setattr__
    self[attr] = value
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 567, in __setitem__
    self.set_attribute(name, value)
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 165, in set_attribute
    value = validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1639, in validate_and_convert_types
    validate_and_convert_types(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1593, in validate_and_convert_types
    return attempt_convert_item(
  File "/home/user/.cache/pypoetry/virtualenvs/datadog-cost-allocation-8apYjUwq-py3.9/lib/python3.9/site-packages/datadog_api_client/model_utils.py", line 1497, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes, key_type=key_type)
datadog_api_client.exceptions.ApiTypeError: Invalid type for variable '0'. Required value type is str and passed type was NoneType at ['received_data']['host_list'][526]['meta']['nix_v'][0]
```

**Screenshots**

Not sure if this helps :man_shrugging: 
![screenshot-1657137957](https://user-images.githubusercontent.com/54455959/177634453-993e0928-458d-4bc4-b21b-0743360deece.png)

**Environment and Versions (please complete the following information):**

```
[[package]]
name = "datadog-api-client"
version = "1.11.0"
```
- python3.9
- debian

**Additional context**

The null value first shows up here: https://github.com/DataDog/datadog-api-client-python/blob/master/src/datadog_api_client/model_utils.py#L1603
The exception happens here https://github.com/DataDog/datadog-api-client-python/blob/1.11.0/src/datadog_api_client/model_utils.py#L1497 since `must_convert` is True. Maybe the conversion should be optional?

**Comment by therve** [comment]
Hi,

I can't seem to be able to reproduce. nixV shouln't only be set on linux hosts indeed, but the key should be missing, not set to None. Continuing to investigate.

**Comment by austinmitchem** [comment]
This bug is still present in version `2.3.0`. I am receiving the same error as the original post:

```
  File "/opt/homebrew/lib/python3.10/site-packages/datadog_api_client/model_utils.py", line 1497, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes, key_type=key_type)
datadog_api_client.exceptions.ApiTypeError: Invalid type for variable '0'. Required value type is str and passed type was NoneType at ['received_data']['host_list'][156]['meta']['nix_v'][0]
```

It seems to be caused when the API returns a host with the following metadata:
```
"nixV": [
    null,
    null,
    null
],
```

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-api-client-python/pull/1261

**Comment by AnalogJ** [comment]
@skarimo this seems to still be an issue:

```
Invalid type for variable '1'. Required value type is one of [NoneType, str] and passed type was list at ['received_data']['host_list'][73]['meta']['mac_v'][1]
```

this failure occurs on `2.8.0` and `2.6.0`
