### ISSUE TITLE
Proxy the API doesn't accept self signed certificate

### ISSUE THREAD

**Issue by mpgn** [DataDog/datadog-api-client-python#1179]
**Describe the bug**

I try to proxy the API request to BURP in order to debug and replay quickly some request but the datadog api client doesn't accept self signed certificate. Is there a workaround ?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 701, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 997, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bonclay/sigma/lucca-scripts/synchro-datadog.py", line 31, in <module>
    response = api_instance.list_security_monitoring_rules()
  File "/usr/local/lib/python3.10/dist-packages/datadog_api_client/v2/api/security_monitoring_api.py", line 658, in list_security_monitoring_rules
    return self._list_security_monitoring_rules_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datadog_api_client/api_client.py", line 712, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/datadog_api_client/api_client.py", line 326, in call_api
    return self._call_api(
  File "/usr/local/lib/python3.10/dist-packages/datadog_api_client/api_client.py", line 99, in _call_api
    response = self.rest_client.request(
  File "/usr/local/lib/python3.10/dist-packages/datadog_api_client/rest.py", line 195, in request
    r = self.pool_manager.request(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 533, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 814, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 814, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 814, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.datadoghq.com', port=443): Max retries exceeded with url: /api/v2/security_monitoring/rules (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)')))
```

**To Reproduce**

`configuration.proxy = "http://127.0.0.1:8080"`

**Expected behavior**
A parameter to accept self signed certificate

**Comment by mpgn** [comment]
Oups found the solution `configuration.verify_ssl = False`
