### ISSUE TITLE
Async client throws on paginated endpoint calls

### ISSUE THREAD

**Issue by garretruh** [DataDog/datadog-api-client-python#1950]
**Describe the bug**
Calling paginated API endpoints with `AsyncApiClient` results in the exception:

```
AttributeError: 'Endpoint' object has no attribute 'get_pagination_params'
```

**To Reproduce**
1.  Create a client using `AsyncApiClient`
2. Invoked a paginated endpoint

```python
import asyncio
from datadog_api_client import AsyncApiClient, Configuration
from datadog_api_client.v2.api.service_definition_api import ServiceDefinitionApi


async def main():
    client = ServiceDefinitionApi(AsyncApiClient(Configuration()))
    services = []
    async for service in client.list_service_definitions_with_pagination():
        services.append(service)
    print(len(services))


if __name__ == "__main__":
    asyncio.run(main())
```

```shell
$ python main.py
Traceback (most recent call last):
  File "/Users/garret/Dev/datadog_test_case/main.py", line 15, in <module>
    asyncio.run(main())
  File "/Users/garret/.pyenv/versions/3.11.7/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/garret/.pyenv/versions/3.11.7/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garret/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/garret/Dev/datadog_test_case/main.py", line 9, in main
    async for service in client.list_service_definitions_with_pagination():
  File "/Users/garret/Dev/datadog_test_case/.venv/lib/python3.11/site-packages/datadog_api_client/api_client.py", line 634, in call_api_paginated
    params = pagination["endpoint"].get_pagination_params(pagination["kwargs"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Endpoint' object has no attribute 'get_pagination_params'
```

**Expected behavior**
API call succeeds.

**Environment and Versions (please complete the following information):**
macOS 14.4.1
Python 3.11.7
datadog-api-client 2.24.1

**Comment by skarimo** [comment]
Thanks again for the contribution!
