### ISSUE TITLE
Can't use requests with datadog-api

### ISSUE THREAD

**Issue by stenius** [DataDog/datadog-api-client-python#467]
When requests.py is imported with the datadog-api, requests do not work.

**To Reproduce**
Import requests.py and follow one of the examples from the documentation.

**Expected behavior**
The datadog-api library working with other business logic that uses the popular requests library.

**Screenshots**
```
Traceback (most recent call last):
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...

  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/api/logs_api.py", line 260, in list_logs
    return self._list_logs_endpoint.call_with_http_info(**kwargs)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/api_client.py", line 861, in call_with_http_info
    collection_formats=params["collection_format"],
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/api_client.py", line 402, in call_api
    _check_type,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/api_client.py", line 189, in __call_api
    _request_timeout=_request_timeout,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/api_client.py", line 473, in request
    body=body,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/rest.py", line 308, in POST
    body=body,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/datadog_api_client/v2/rest.py", line 161, in request
    headers=headers,
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/paulstenius/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.datadoghq.com', port=443): Max retries exceeded with url: /api/v2/logs/events/search (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Environment and Versions**
requests==2.22.0
datadog-api-client==1.0.0

**Comment by therve** [comment]
Hello,

Can you describe your problem a little bit more? datadog-api-client-python doesn't use requests, and it's nowhere in that traceback. Do you mean when you use requests it works? It's possible there is a certificate issue locally. It certainly works in all our environments. What's your certifi version?

**Comment by therve** [comment]
Hello,

Closing that one, feel free to reopen with more information. Thanks.
