### ISSUE TITLE
list_tests() - TypeError: __init__() missing 1 required positional argument: 'example'

### ISSUE THREAD

**Issue by mariuscoto** [DataDog/datadog-api-client-python#480]
**Describe the bug**
The `list_tests()` example from [here](https://datadoghq.dev/datadog-api-client-python/v1/SyntheticsApi/#list_tests):
```
import os
from dateutil.parser import parse as dateutil_parser
from datadog_api_client.v1 import ApiClient, ApiException, Configuration
from datadog_api_client.v1.api import synthetics_api
from datadog_api_client.v1.models import *
from pprint import pprint
# See configuration.py for a list of all supported configuration parameters.
configuration = Configuration()

# Enter a context with an instance of the API client
with ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = synthetics_api.SyntheticsApi(api_client)

    # example, this endpoint has no required or optional parameters
    try:
        # Get the list of all tests
        api_response = api_instance.list_tests()
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling SyntheticsApi->list_tests: %s\n" % e)
```

Returns this error: `TypeError: __init__() missing 1 required positional argument: 'example'`

**Environment and Versions (please complete the following information):**
`datadog-api-client==1.1.0`

**Additional context**
Full stack trace:
```
Traceback (most recent call last):
  File "/Users/marius/bin/datadog", line 8, in <module>
    sys.exit(main())
  File "/marius/lib/python3.8/site-packages/gdev/contrib/datadog/__main__.py", line 120, in main
    run_cli_with_reporting(datadog, 'datadog', cfg.get_username(), owner='sre')
  File "/marius/lib/python3.8/site-packages/gdev/cli_utils.py", line 16, in run_cli_with_reporting
    raise e
  File "/marius/lib/python3.8/site-packages/gdev/cli_utils.py", line 13, in run_cli_with_reporting
    tool(prog_name=prog_name)
  File "/marius/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/marius/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/marius/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/marius/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/marius/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/marius/lib/python3.8/site-packages/gdev/contrib/datadog/__main__.py", line 86, in pull
    dogman.pull()
  File "/marius/lib/python3.8/site-packages/gdev/controllers/datadog/controller.py", line 127, in pull
    self.handler.pull()
  File "/marius/lib/python3.8/site-packages/gdev/controllers/datadog/monitor.py", line 566, in pull
    api_response = api_instance.list_tests()
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/api/synthetics_api.py", line 1966, in list_tests
    return self._list_tests_endpoint.call_with_http_info(**kwargs)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py", line 842, in call_with_http_info
    return self.api_client.call_api(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py", line 386, in call_api
    return self.__call_api(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py", line 214, in __call_api
    return_data = self.deserialize(response_data, response_type, _check_type)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py", line 307, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1305, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1194, in attempt_convert_item
    return deserialize_model(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1110, in deserialize_model
    return model_class(**kw_args)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1478, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_list_tests_response.py", line 170, in __init__
    setattr(self, var_name, var_value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 316, in __setitem__
    self.set_attribute(name, value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 119, in set_attribute
    value = validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1355, in validate_and_convert_types
    validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1305, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1194, in attempt_convert_item
    return deserialize_model(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1110, in deserialize_model
    return model_class(**kw_args)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1478, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_test_details.py", line 213, in __init__
    setattr(self, var_name, var_value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 316, in __setitem__
    self.set_attribute(name, value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 119, in set_attribute
    value = validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1305, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1194, in attempt_convert_item
    return deserialize_model(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1110, in deserialize_model
    return model_class(**kw_args)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1478, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_test_config.py", line 190, in __init__
    setattr(self, var_name, var_value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 316, in __setitem__
    self.set_attribute(name, value)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 119, in set_attribute
    value = validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1355, in validate_and_convert_types
    validate_and_convert_types(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1305, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1194, in attempt_convert_item
    return deserialize_model(
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1110, in deserialize_model
    return model_class(**kw_args)
  File "/marius/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py", line 1478, in wrapped_init
    return fn(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'example'
```

**Comment by therve** [comment]
Hello,

Are you sure you're running versions 1.1.0? https://github.com/DataDog/datadog-api-client-python/pull/457 should have fixed your issue but it's supposed to be included in that version. Trying to reproduce on my side.

**Comment by alec-jumpstart** [comment]
got this as well, it turned out that while `datadog-api-client==1.1.0` was specified in my requirements.txt, i still had 1.0.0 installed from when I was doing testing originally. Uninstalling 1.0.0 and switching to 1.1.0 fixed it!

**Comment by therve** [comment]
Thanks @alec-jumpstart for the confirmation! Closing this one for now, let me know if that still happens.
