### ISSUE TITLE
Get an SLO's history is not working with Target as expected 

### ISSUE THREAD

**Issue by Dina22768** [DataDog/datadog-api-client-python#481]
Describe the bug 
I am trying to use Get an SLO's history API with Target to get the value of error_budget_remaining but it is not working. I used the same example in [here]( https://docs.datadoghq.com/api/latest/service-level-objectives/#get-an-slos-history)

Filled the params as follows: 
```
slo_id = "xxxxxxx" # str | The ID of the service level objective object.
from_ts = int(time.time()) - (60 * 60 * 24 * 30) # int | The from timestamp for the query window in epoch seconds.
to_ts = int(time.time()) # int | The `to` timestamp for the query window in epoch seconds.
target = 90.25 # float | The SLO target. If `target` is passed in, the response will include the error budget that remains.


The error I am getting when I try this API :         

api_response = api_instance.get_slo_history(slo_id, from_ts, to_ts, target=target)

 
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./app/routers/status.py", line 43, in test_dd_status
    api_response = api_instance.get_slo_history(slo_id, from_ts, to_ts, target=target)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/api/service_level_objectives_api.py", line 664, in get_slo_history
    return self._get_slo_history_endpoint.call_with_http_info(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/api_client.py", line 861, in call_with_http_info
    collection_formats=params["collection_format"],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/api_client.py", line 402, in call_api
    _check_type,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/api_client.py", line 214, in __call_api
    return_data = self.deserialize(response_data, response_type, _check_type)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/api_client.py", line 308, in deserialize
    received_data, response_type, ["received_data"], True, _check_type, configuration=self.configuration
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1317, in validate_and_convert_types
    check_type=_check_type,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1206, in attempt_convert_item
    raise conversion_exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1199, in attempt_convert_item
    input_value, valid_class, path_to_item, check_type, configuration, spec_property_naming
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1114, in deserialize_model
    return model_class(**kw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1482, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model/slo_history_response.py", line 175, in __init__
    setattr(self, var_name, var_value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 318, in __setitem__
    self.set_attribute(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 125, in set_attribute
    configuration=self._configuration,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1317, in validate_and_convert_types
    check_type=_check_type,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1206, in attempt_convert_item
    raise conversion_exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1199, in attempt_convert_item
    input_value, valid_class, path_to_item, check_type, configuration, spec_property_naming
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1114, in deserialize_model
    return model_class(**kw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1482, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model/slo_history_response_data.py", line 205, in __init__
    setattr(self, var_name, var_value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 318, in __setitem__
    self.set_attribute(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 125, in set_attribute
    configuration=self._configuration,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1385, in validate_and_convert_types
    configuration=configuration,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1317, in validate_and_convert_types
    check_type=_check_type,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1206, in attempt_convert_item
    raise conversion_exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1199, in attempt_convert_item
    input_value, valid_class, path_to_item, check_type, configuration, spec_property_naming
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1114, in deserialize_model
    return model_class(**kw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1482, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model/slo_threshold.py", line 176, in __init__
    self.timeframe = timeframe
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 318, in __setitem__
    self.set_attribute(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 125, in set_attribute
    configuration=self._configuration,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1317, in validate_and_convert_types
    check_type=_check_type,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1206, in attempt_convert_item
    raise conversion_exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1199, in attempt_convert_item
    input_value, valid_class, path_to_item, check_type, configuration, spec_property_naming
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1109, in deserialize_model
    return model_class(model_data, **kw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 1482, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model/slo_timeframe.py", line 171, in __init__
    self.value = value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 143, in __setattr__
    self[attr] = value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 265, in __setitem__
    self.set_attribute(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 128, in set_attribute
    check_allowed_values(self.allowed_values, (name,), value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datadog_api_client/v1/model_utils.py", line 645, in check_allowed_values
    % (input_variable_path[0], input_values, these_allowed_values)
datadog_api_client.v1.exceptions.ApiValueError: Invalid value for `value` (custom), must be one of ['7d', '30d', '90d']
```

**Comment by therve** [comment]
Fixed in #497
