### ISSUE TITLE
Receiving 'invalid' value for query error when creating anomaly monitor

### ISSUE THREAD

**Issue by imann24** [DataDog/datadog-api-client-python#764]
**Describe the bug**
I'm creating an anomaly monitor using the `MonitorsApi` API. I receive a 400 error telling me that my query is invalid

Label the issue properly.
- Add `severity/normal` label. (I don't have permissions to edit the labels on this issue myself)

**To Reproduce**
1. Create a monitor of a type `"query alert"`
2. Provide a valid `anomaly` query string for the `query` field

See code sample:
```python
from dotenv import load_dotenv
from datadog_api_client.v1 import ApiClient, Configuration
from datadog_api_client.v1.api.monitors_api import MonitorsApi
from datadog_api_client.v1.model.monitor import Monitor
from datadog_api_client.v1.model.monitor_type import MonitorType

load_dotenv()

monitor = Monitor(
    name="Reproduce Anomaly Creation Error",
    type=MonitorType("query alert"),
    query="avg(last_1d):anomalies(sum:metric_name{placement:tag}.as_count(),'agile',2,direction='below',alert_window='last_1h',interval=300,count_default_zero='true',seasonality='hourly')>=1",
    message="repro"
)

configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = MonitorsApi(api_client)
    api_instance.create_monitor(body=monitor)
```

**Expected behavior**
Anomaly monitor is created

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - Using library version `1.7.0`
  - Python 3.9.9, `poetry` package manager, [python-dotenv](https://pypi.org/project/python-dotenv/) library

**Additional context**
**Error Log**:
```
Traceback (most recent call last):
  File "/Users/isaiah/workspace/tool/datadog/datadog-alert-generator/simple_repro.py", line 19, in <module>
    api_instance.create_monitor(body=monitor)
  File "/Users/isaiah/Library/Caches/pypoetry/virtualenvs/datadog-alert-generator-saQsB-sU-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/api/monitors_api.py", line 406, in create_monitor
    return self._create_monitor_endpoint.call_with_http_info(**kwargs)
  File "/Users/isaiah/Library/Caches/pypoetry/virtualenvs/datadog-alert-generator-saQsB-sU-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/api_client.py", line 705, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/isaiah/Library/Caches/pypoetry/virtualenvs/datadog-alert-generator-saQsB-sU-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/api_client.py", line 370, in call_api
    return self._call_api(
  File "/Users/isaiah/Library/Caches/pypoetry/virtualenvs/datadog-alert-generator-saQsB-sU-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/api_client.py", line 127, in _call_api
    response = self.rest_client.request(
  File "/Users/isaiah/Library/Caches/pypoetry/virtualenvs/datadog-alert-generator-saQsB-sU-py3.9/lib/python3.9/site-packages/datadog_api_client/v1/rest.py", line 221, in request
    raise ApiException(http_resp=r)
datadog_api_client.v1.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 05 Jan 2022 00:27:16 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'x-ratelimit-name': 'post_monitors', 'x-ratelimit-remaining': '499', 'x-ratelimit-limit': '500', 'x-ratelimit-period': '10', 'x-ratelimit-reset': '4', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=15724800;', 'content-security-policy': "frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report", 'x-frame-options': 'SAMEORIGIN'})
HTTP response body: {'errors': ["The value provided for parameter 'query' is invalid"]}
```

**Comment by therve** [comment]
Hi,

Can you open a support ticket? This seems related to the monitor query format, not the python SDK. Thank you.

**Comment by therve** [comment]
I think you need to have an `options` with `thresholds` defined for the query to be parsed properly.

**Comment by imann24** [comment]
Thanks Thomas. That fixed the issue. Here's the revised code sample in-case anyone else comes across this:
```python
from dotenv import load_dotenv
from datadog_api_client.v1 import ApiClient, Configuration
from datadog_api_client.v1.api.monitors_api import MonitorsApi
from datadog_api_client.v1.model.monitor import Monitor
from datadog_api_client.v1.model.monitor_type import MonitorType
from datadog_api_client.v1.model.monitor_options import MonitorOptions
from datadog_api_client.v1.model.monitor_threshold_window_options import MonitorThresholdWindowOptions


load_dotenv()

options = MonitorOptions(
    threshold_windows=MonitorThresholdWindowOptions(
        recovery_window="last_15m",
        trigger_window="last_1h"
    )
)

monitor = Monitor(
    name="Corrected Anomaly Creation Error",
    type=MonitorType("query alert"),
    query="avg(last_1d):anomalies(sum:metric_name{placement:tag}.as_count(),'agile',2,direction='below',alert_window='last_1h',interval=300,count_default_zero='true',seasonality='hourly')>=1",
    message="fix",
    options=options
)

configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = MonitorsApi(api_client)
    api_instance.create_monitor(body=monitor)
```
